launchAtLogin: true
hotkey: cmd+f7

PATH:
  - /opt/homebrew/bin

panel:
  keepCentered: true

search:
  program:
    exec: fzf
    args: ["--read0", "--print0", "--delimiter=:", "--nth=2..", "-f"] 

modules:
  - switcher:
      name: ""
  - app-search:
      maxResults: 3

  - /native/controller:
      trigger: ^sc (.*)
  - /native/childProcessMonitor:
      trigger: ^mon (.*)
  - /native/indexer

  - control-center
  - clipboard:
      trigger: ^p (.*)
  - math
  - keychain
  - unicode
