launchAtLogin: true
hotkey: cmd+f7

PATH:
  - /opt/homebrew/bin

panel:
  keepCentered: true

search:
  program:
    exec: fzf
    args: ["--read0", "--print0", "--delimiter=:", "--nth=2..", "-f"] 

modules:
  - switcher:
      name: ""
      envOptions:
        IGNORED_APPS: "net.kovidgoyal.kitty,tracesOf.Uebersicht"
  - app-search:
      maxResults: 3

  - /native/controller:
      trigger: ^sc (.*)
  - /native/childProcessMonitor:
      trigger: ^mon (.*)
  - /native/indexer

  - control-center
  - clipboard:
      trigger: ^p (.*)
  - math
  - keychain
  - unicode
  - safari-histmarks
  - safari-tabs
  - pkill
  - timer

  - /inline/date-copy:
      name: "Today's Date"
      trigger: "^date (.*)"
      suppressOthers: true
      isSearchDisabled: true
      reloadsOnChange: false
      source:
        program:
          exec: zsh
          args:
            - -c
            - |
              echo "[{ \"title\": \"$(date +%y-%m-%d)\" }]"
      sink:
        program:
          exec: zsh
          args:
            - -c
            - |
              printf {{ title }} | pbcopy && printf closePanel
      defaultSymbol: 􀉃
