:filetype plugin on
set clipboard=unnamed
set ttimeoutlen=5             " key code delay
set viminfo+=n~/.vim/viminfo
set rtp+=/usr/local/opt/fzf   " install fzf
set nomodeline
set switchbuf=usetab
" silent! helptags ALL

