#!/bin/zsh

battery=$(pmset -g batt)

if [[ -z "$battery" || "$battery" == *charged* ]]; then
    echo ""
    exit 0
fi

[[ "$battery" == *discharging* ]] || printf '⚡ '

if [[ "$1" == "--percentage" || "$1" == "-p" ]]; then
    grep -o '\d\+%' <<< $battery
else
    grep -o '\d\+:\d\+' <<< $battery || grep -o '\d\+%' <<< $battery
fi
