#!/usr/bin/env python3

import subprocess

whitelist = ['Finder', 'iTerm2', 'Mail']

def running_apps():
    result = subprocess.run(['osascript', '-e',
        'tell application "System Events" to log (get the name of every process where background only is false)'], capture_output=True
    )
    return result.stderr.decode('utf-8')[:-1].split(', ')

def quit_apps(names):
    subprocess.run(['osascript', '-e', f'''\
        repeat with a in {{{ ', '.join([f'"{name}"' for name in names]) }}}
            tell application a to quit
        end repeat\
    '''], capture_output=True)

if __name__ == '__main__':
    quit_apps(app for app in running_apps() if app not in whitelist)

