#!/bin/sh

dotfiles_dir="$HOME/_dotfiles"
dotfiles=`find $dotfiles_dir -type f -not -path '*.git/*' -not -path '*no-sync/*' -not -name '.DS_Store' -not -path '*.fbms/*'`

for f in $dotfiles; do
    inst=$(echo $f | sed "s,$dotfiles_dir,$HOME,")

    if ! cmp $f $inst &> /dev/null; then
        name=$(echo $f | sed "s,$dotfiles_dir/,,")
        read -n 1 -p "install $name? (y/*) " answer
        if [[ $answer =~ [Yy] ]]; then
            mkdir -p "$(dirname $inst)"
            cp "$f" "$inst"
        fi
        printf "\n"
    fi
done

