#!/bin/sh

[[ -n "$1" ]] && CURPOS=$1 || CURPOS="0, 0"

vim - \
    --not-a-term \
    '+silent! w! /tmp/vim_ansi' \
    '+silent! term ++hidden ++open cat /tmp/vim_ansi' \
    "+autocmd BufEnter * only | call setpos('.', [0, $CURPOS, 0])"
