require"events"
require"smart-magnify"
require"window"
dofile"/Users/jannisbaum/.config/synapse/modules/control-center/hammerspoon.lua"
dofile"/Users/jannisbaum/.config/synapse/modules/timer/hammerspoon.lua"
