require"events"
require"window"
require"desktop_background"
dofile"/Users/jannisbaum/.config/synapse/modules/control-center/hammerspoon.lua"
dofile"/Users/jannisbaum/.config/synapse/modules/timer/hammerspoon.lua"
