#!/bin/zsh

WRITER_PID="$(test -f ~/.config/kitty/writer/.pid \
    && cat ~/.config/kitty/writer/.pid \
    || echo 0)"

if [[ "$1" == "hidden" ]]; then
    ~/.local/bin/set-kitty mismatching $WRITER_PID hidden
elif [[ "$1" == "active" ]]; then
    ~/.local/bin/set-kitty mismatching $WRITER_PID active
fi
