#!/bin/zsh

echo $KITTY_PID > ~/.config/kitty/writer/.pid

F=$(mktemp).md

/usr/local/bin/vim $F \
    '+set laststatus=1' \
    '+startinsert' \
    '+echo ""'

printf "%s" "$(cat $F)" | pbcopy

rm $F
~/.bin/set-kitty matching $KITTY_PID hidden
